### ISSUE TITLE
Add support for PHP7

### ISSUE THREAD

**Issue by markdorison** [weareinteractive/ansible-php5-newrelic#5]
## Description 
This role fails when installed with PHP7. This may just be due to pathing issues.

**Comment by franklinkim** [comment]
hi, yeah, haven't tested it on PHP7 yet. Any PR are welcome.

**Comment by SirTimmyTimbit** [comment]
Installed just fine for me. Keep in mind the paths changed for PHP7

Replace

`php5_newrelic_config_dest: /etc/php5/mods-available`

with

`php5_newrelic_config_dest: /etc/php/7.0/mods-available`

**Comment by franklinkim** [comment]
ok, thank. I added a note.
