### ISSUE TITLE
Error with iteritems() at "Configuring module" task

### ISSUE THREAD

**Issue by silenci** [weareinteractive/ansible-php5-newrelic#8]
TASK [franklinkim.php5-newrelic : Configuring module] ******************************************************************************************************************
fatal: [x.x.x.x]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"}

I've found this:

https://docs.ansible.com/ansible/2.5/dev_guide/testing/sanity/no-dict-iteritems.html

Changed iteritems() by items() at line 671 of newrelic.ini.j2 and seems like fixed it.

**Comment by o0Silas0o** [comment]
I am getting the same issue, and the suggested fix works. Any chance of getting that added to the Role?

**Comment by franklinkim** [comment]
THX
